//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./ap_types');
//HELPER FUNCTIONS AND STRUCTURES

var APService_login_im_args = function(args) {
  this.param = null;
  if (args) {
    if (args.param !== undefined && args.param !== null) {
      this.param = new ttypes.LoginParam(args.param);
    }
  }
};
APService_login_im_args.prototype = {};
APService_login_im_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.param = new ttypes.LoginParam();
        this.param.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

APService_login_im_args.prototype.write = function(output) {
  output.writeStructBegin('APService_login_im_args');
  if (this.param !== null && this.param !== undefined) {
    output.writeFieldBegin('param', Thrift.Type.STRUCT, 1);
    this.param.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var APService_login_im_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.LoginResult(args.success);
    }
  }
};
APService_login_im_result.prototype = {};
APService_login_im_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.LoginResult();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

APService_login_im_result.prototype.write = function(output) {
  output.writeStructBegin('APService_login_im_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var APService_qAppStoreS_args = function(args) {
  this.st = null;
  this.param = null;
  if (args) {
    if (args.st !== undefined && args.st !== null) {
      this.st = new ttypes.SessionTicket(args.st);
    }
    if (args.param !== undefined && args.param !== null) {
      this.param = new ttypes.AppStoreParam(args.param);
    }
  }
};
APService_qAppStoreS_args.prototype = {};
APService_qAppStoreS_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.st = new ttypes.SessionTicket();
        this.st.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.param = new ttypes.AppStoreParam();
        this.param.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

APService_qAppStoreS_args.prototype.write = function(output) {
  output.writeStructBegin('APService_qAppStoreS_args');
  if (this.st !== null && this.st !== undefined) {
    output.writeFieldBegin('st', Thrift.Type.STRUCT, 1);
    this.st.write(output);
    output.writeFieldEnd();
  }
  if (this.param !== null && this.param !== undefined) {
    output.writeFieldBegin('param', Thrift.Type.STRUCT, 2);
    this.param.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var APService_qAppStoreS_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.AppStoreRet(args.success);
    }
  }
};
APService_qAppStoreS_result.prototype = {};
APService_qAppStoreS_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.AppStoreRet();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

APService_qAppStoreS_result.prototype.write = function(output) {
  output.writeStructBegin('APService_qAppStoreS_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var APServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
APServiceClient.prototype = {};
APServiceClient.prototype.seqid = function() { return this._seqid; };
APServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };
APServiceClient.prototype.login_im = function(param, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_login_im(param);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_login_im(param);
  }
};

APServiceClient.prototype.send_login_im = function(param) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('login_im', Thrift.MessageType.CALL, this.seqid());
  var args = new APService_login_im_args();
  args.param = param;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

APServiceClient.prototype.recv_login_im = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new APService_login_im_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('login_im failed: unknown result');
};
APServiceClient.prototype.qAppStoreS = function(st, param, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_qAppStoreS(st, param);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_qAppStoreS(st, param);
  }
};

APServiceClient.prototype.send_qAppStoreS = function(st, param) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('qAppStoreS', Thrift.MessageType.CALL, this.seqid());
  var args = new APService_qAppStoreS_args();
  args.st = st;
  args.param = param;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

APServiceClient.prototype.recv_qAppStoreS = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new APService_qAppStoreS_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('qAppStoreS failed: unknown result');
};
var APServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
}
;
APServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}
;
APServiceProcessor.prototype.process_login_im = function(seqid, input, output) {
  var args = new APService_login_im_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.login_im.length === 1) {
    Q.fcall(this._handler.login_im, args.param)
      .then(function(result) {
        var result_obj = new APService_login_im_result({success: result});
        output.writeMessageBegin("login_im", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("login_im", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.login_im(args.param, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new APService_login_im_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("login_im", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("login_im", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
APServiceProcessor.prototype.process_qAppStoreS = function(seqid, input, output) {
  var args = new APService_qAppStoreS_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.qAppStoreS.length === 2) {
    Q.fcall(this._handler.qAppStoreS, args.st, args.param)
      .then(function(result) {
        var result_obj = new APService_qAppStoreS_result({success: result});
        output.writeMessageBegin("qAppStoreS", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("qAppStoreS", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.qAppStoreS(args.st, args.param, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new APService_qAppStoreS_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("qAppStoreS", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("qAppStoreS", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
